(function(){
'use strict';
const KEY_NAMES=['tomtomApiKey','tomtom_api_key','tomtomKey','tt_api_key'];
const KEY='tomtomApiKey';
const URBAN_INTERVAL=3*60*1000;
const HIGHWAY_INTERVAL=8*60*1000;
const MAX_QUERIES=2300;
const COUNT_KEY='tomtomQueryCount';
let lastQuery=0,lastLat=null,lastLon=null,lastLimit=null,lastRoad='',lastRoadType='unknown',lastQueryType='unknown';
function key(){for(const k of KEY_NAMES){const v=(localStorage.getItem(k)||'').trim();if(v)return v;}return ''}
function saveKey(v){localStorage.setItem(KEY,v.trim())}
function count(){return Number(localStorage.getItem(COUNT_KEY)||0)}
function canQuery(){return count()<MAX_QUERIES}
function incQuery(){localStorage.setItem(COUNT_KEY,String(count()+1));window.dispatchEvent(new CustomEvent('tomtomQueryCountUpdated',{detail:{used:count(),remaining:Math.max(0,MAX_QUERIES-count())}}))}
function hav(a,b,c,d){const R=6371,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function kmh(v){const n=Number(v);return Number.isFinite(n)&&n>=0?n*3.6:null}
function isHighway(a){const u=String((a&&a.routeType)||'').toLowerCase();const roadUse=String((a&&a.roadUse)||'').toLowerCase();const name=String((a&&(a.streetName||a.street))||'').toLowerCase();return /motorway|trunk|highway|freeway|expressway|toll|motorway_link|trunk_link/.test(u+' '+roadUse+' '+name)}
function interval(){return lastRoadType==='highway'?HIGHWAY_INTERVAL:URBAN_INTERVAL}
function ensure(){if(document.getElementById('tt-speed-card'))return;const host=document.querySelector('#av-trip-panel')||document.querySelector('main');if(!host)return;const d=document.createElement('div');d.id='tt-speed-card';d.className='card';d.style.marginTop='6px';d.innerHTML='<div style="font-weight:800;margin-bottom:8px">🚦 Velocidade da via</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><div class="metric"><span>Velocidade atual</span><b id="tt-current-speed">—</b></div><div class="metric"><span>Limite TomTom</span><b id="tt-speed-limit">—</b></div></div><div id="tt-speed-status" class="note" style="margin-top:8px">TomTom aguardando localização.</div><div id="tt-query-counter" class="note" style="margin-top:6px">Consultas TomTom: 0/2300</div><div style="display:flex;gap:8px;margin-top:9px"><button id="tt-key-btn" class="secondary" style="flex:1">Configurar TomTom</button></div>';host.insertAdjacentElement('afterend',d);document.getElementById('tt-key-btn').onclick=config;renderCounter()}
function config(){let v=prompt('Cole a chave da API TomTom. Ela ficará salva somente neste aparelho.','');if(v&&v.trim()){saveKey(v);setStatus('Chave TomTom salva. Aguardando GPS...');if(lastLat!=null)query(lastLat,lastLon,0)}}
function setStatus(t,cls){const e=document.getElementById('tt-speed-status');if(e){e.textContent=t;e.className='note '+(cls||'')}}
function renderCounter(){const e=document.getElementById('tt-query-counter');if(e)e.textContent='Consultas TomTom: '+count()+'/'+MAX_QUERIES+' • Restantes: '+Math.max(0,MAX_QUERIES-count())}
function renderSpeed(v){const e=document.getElementById('tt-current-speed');if(e)e.textContent=v==null?'—':Math.round(v)+' km/h';const l=document.getElementById('tt-speed-limit');if(l)l.textContent=lastLimit==null?'—':lastLimit+' km/h';const s=document.getElementById('tt-speed-status');if(s){if(lastLimit==null){s.textContent=lastRoad?(lastRoad+' • Limite não disponível'):'Limite TomTom não disponível';s.className='note'}else{const diff=v==null?0:v-lastLimit;s.textContent=(lastRoad?(lastRoad+' • '):'')+(diff>3?'Acima do limite em '+Math.round(diff)+' km/h':'Dentro do limite')+' • '+(lastRoadType==='highway'?'Rodovia':'Urbana');s.className='note '+(diff>3?'warn':'')}}renderCounter()}
async function query(lat,lon,speed){const k=key();if(!k){setStatus('TomTom não configurado. Toque em Configurar TomTom.');return}if(!canQuery()){setStatus('Limite de 2.300 consultas TomTom atingido.','warn');return}const now=Date.now();const wait=interval();if(lastQuery&&now-lastQuery<wait){const mins=Math.ceil((wait-(now-lastQuery))/60000);setStatus('Próxima consulta TomTom em aproximadamente '+mins+' min.');return}if(lastLat!=null&&hav(lastLat,lastLon,lat,lon)<0.08){setStatus('Aguardando intervalo mínimo entre consultas TomTom.');return}lastLat=lat;lastLon=lon;try{const u='https://api.tomtom.com/search/2/reverseGeocode/'+encodeURIComponent(lat+','+lon)+'.json?key='+encodeURIComponent(k)+'&returnSpeedLimit=true&returnRoadUse=true&radius=100';const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);incQuery();lastQuery=now;const j=await r.json();const a=j&&j.addresses&&j.addresses[0]&&j.addresses[0].address;if(!a){lastLimit=null;lastRoad='';setStatus('TomTom não encontrou limite para este ponto.');return}lastRoadType=isHighway(a)?'highway':'urban';lastQueryType=lastRoadType;let raw=a.speedLimit||'';const m=String(raw).match(/([0-9]+(?:\.[0-9]+)?)\s*(KPH|MPH)/i);if(m){let n=Number(m[1]);if(m[2].toUpperCase()==='MPH')n=n*1.609344;lastLimit=Math.round(n)}else lastLimit=null;lastRoad=a.streetName||a.street||'';localStorage.setItem('tomtomLast',JSON.stringify({limit:lastLimit,road:lastRoad,roadType:lastRoadType,lat,lon,at:new Date().toISOString(),queryCount:count()}));window.dispatchEvent(new CustomEvent('tomtomSpeedLimitUpdated',{detail:{limit:lastLimit,road:lastRoad,roadType:lastRoadType}}));renderSpeed(speed)}catch(e){setStatus('Não foi possível atualizar o limite TomTom agora.','warn')}}
function gps(data){try{const d=typeof data==='string'?JSON.parse(data):data;const lat=Number(d.lat),lon=Number(d.lon);let s=Number(d.speed);s=s>=0?kmh(s):null;renderSpeed(s);if(Number.isFinite(lat)&&Number.isFinite(lon))query(lat,lon,s)}catch(e){}}
function patch(){ensure();const old=window.nativeGpsUpdate;if(typeof old==='function'&&!old.__tt){const f=function(x){old.apply(this,arguments);gps(x)};f.__tt=true;window.nativeGpsUpdate=f}if(navigator.geolocation)navigator.geolocation.watchPosition(p=>gps({lat:p.coords.latitude,lon:p.coords.longitude,speed:p.coords.speed}),()=>{}, {enableHighAccuracy:true,maximumAge:3000,timeout:10000})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patch);else patch();setInterval(ensure,1500);window.tomtomSpeedLimit={query,config,getUsage:()=>({used:count(),remaining:Math.max(0,MAX_QUERIES-count())})};
})();