(function(){
'use strict';
const MAX=2300,CITY=180000,ROAD=480000,LAST='av_tomtom_last';
let busy=false,lastRoad=false,lastLat=null,lastLon=null;
const $id=id=>document.getElementById(id);
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
function stateLocal(){try{return JSON.parse(localStorage.getItem('assistente_viagem_v3')||'null')}catch(e){return null}}
function usage(){const s=stateLocal();const used=num(s?.settings?.limitQueries,0);return{used,remaining:Math.max(0,MAX-used)}}
function addMetric(){const grid=document.querySelector('.trip-data-card .grid');if(!grid||document.getElementById('limiteViaDados'))return;const m=document.createElement('div');m.className='metric';m.id='limiteViaDados';m.innerHTML='<span>Limite da via</span><b id="limiteViaDadosValor">-- km/h</b><small id="limiteViaDadosStatus" style="display:block;margin-top:4px;color:var(--muted)">Aguardando TomTom</small><div class="future-space"></div>';const first=grid.querySelector('.metric');if(first&&first.nextElementSibling)grid.insertBefore(m,first.nextElementSibling);else grid.appendChild(m)}
function renderLimit(limit,type,source){addMetric();const v=$id('limiteViaDadosValor'),s=$id('limiteViaDadosStatus'),main=$id('limiteVelocidade'),fonte=$id('fonteLimite'),tipo=$id('tipoVia');if(v)v.textContent=limit?Math.round(limit)+' km/h':'-- km/h';if(main)main.textContent=limit?Math.round(limit)+' km/h':'-- km/h';if(fonte)fonte.textContent=source||'TomTom';if(tipo)tipo.textContent=type||'--';const speed=num(($id('velocidade')?.textContent||'').replace(/[^0-9.,-]/g,'').replace(',','.'),0);if(s){if(limit&&speed>limit){s.textContent='⚠️ Acima do limite';s.className='danger'}else if(limit){s.textContent='Dentro do limite';s.className=''}else{s.textContent='Limite não disponível';s.className=''}}const c=usage();if($id('consultasLimite'))$id('consultasLimite').textContent=c.used+' / '+MAX;if($id('consultasRestantes'))$id('consultasRestantes').textContent=c.remaining;if($id('consultasTomTom'))$id('consultasTomTom').textContent=c.used}
function classify(data){const item=data?.addresses?.[0]||{},a=item.address||{},ru=Array.isArray(item.roadUse)?item.roadUse.map(String):[String(item.roadUse||'')],rn=Array.isArray(a.routeNumbers)?a.routeNumbers:[],text=(ru.join(' ')+' '+rn.join(' ')).toLowerCase();const highway=/limitedaccess|motorway|trunk|highway|freeway|expressway|toll|motorway_link|trunk_link|ramp/.test(text)||rn.length>0;return{road:highway,type:highway?'Rodovia':'Urbana'}}
function extract(data){const item=data?.addresses?.[0]||{},a=item.address||{};for(const v of [item.speedLimit,a.speedLimit,data?.speedLimit]){const m=String(v??'').match(/([0-9]+(?:\.[0-9]+)?)/);if(m){const n=Number(m[1]);if(n>0&&n<300)return n}}return null}
function nextAt(ms){const el=$id('proximaConsultaLimite');if(!el)return;const sec=Math.max(0,Math.ceil(ms/1000));el.textContent=sec>=60?Math.ceil(sec/60)+' min':sec+' s'}
async function consult(lat,lon){if(busy)return;const mode=localStorage.getItem('av_tomtom_mode')||'manual',key=(localStorage.getItem('av_tomtom_api_key')||'').trim();if(mode!=='tomtom'||!key)return;if(usage().used>=MAX){if($id('tomtomStatus'))$id('tomtomStatus').textContent='Limite de 2.300 consultas TomTom atingido.';return}const last=Number(localStorage.getItem(LAST)||0),wait=lastRoad?ROAD:CITY,now=Date.now();if(last&&now-last<wait){nextAt(wait-(now-last));return}busy=true;try{const url='https://api.tomtom.com/search/2/reverseGeocode/'+encodeURIComponent(lat)+','+encodeURIComponent(lon)+'.json?key='+encodeURIComponent(key)+'&returnSpeedLimit=true&returnRoadUse=true';const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json(),cls=classify(data);lastRoad=cls.road;localStorage.setItem(LAST,String(Date.now()));lastLat=lat;lastLon=lon;const lim=extract(data);if(lim&&typeof window.setLimitFromProvider==='function'){window.__avTomTomUpdate=true;window.setLimitFromProvider(lim);window.__avTomTomUpdate=false}renderLimit(lim,cls.type,'TomTom');if($id('tomtomStatus'))$id('tomtomStatus').textContent=lim?'TomTom: limite '+Math.round(lim)+' km/h • '+cls.type+'.':'TomTom consultada, mas sem limite disponível neste trecho.';nextAt(cls.road?ROAD:CITY)}catch(e){if($id('tomtomStatus'))$id('tomtomStatus').textContent='TomTom indisponível no momento.'}finally{busy=false}}
window.maybeConsultTomTom=function(pos){if(!pos||!Number.isFinite(Number(pos.lat))||!Number.isFinite(Number(pos.lon)))return;addMetric();if((localStorage.getItem('av_tomtom_mode')||'manual')!=='tomtom')return;const now=Date.now(),last=Number(localStorage.getItem(LAST)||0),wait=lastRoad?ROAD:CITY;if(!last||now-last>=wait)consult(Number(pos.lat),Number(pos.lon));else nextAt(wait-(now-last))};
window.tomtomSpeedLimit={getUsage:usage,consult};
function hook(){addMetric();const oldRender=window.render;if(typeof oldRender==='function'&&!oldRender.__ttPatch){const r=function(){const x=oldRender.apply(this,arguments);addMetric();const s=stateLocal();const lim=num(s?.settings?.lastLimit,0);renderLimit(lim,lastRoad?'Rodovia':'Urbana',localStorage.getItem('av_tomtom_mode')==='tomtom'?'TomTom':'Manual');return x};r.__ttPatch=true;window.render=r}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(hook,50));else setTimeout(hook,50);setInterval(addMetric,1500);
})();